apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ include "rabbitmq.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
  selector:
    app: {{ include "rabbitmq.name" . }}